export const LOGO =
	"https://help.nflxext.com/helpcenter/OneTrust/oneTrust_production_2025-07-14/consent/87b6a5c0-0104-4e96-a291-092c11350111/01938dc4-59b3-7bbc-b635-c4131030e85f/logos/dd6b162f-1a32-456a-9cfe-897231c7763c/4345ea78-053c-46d2-b11e-09adaef973dc/Netflix_Logo_PMS.png"

export const NETFLIX_USER =
	"https://occ-0-6246-2164.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABStlS0MPUGcy6Ovyeia-3ddnnXNb2Lri4P4H4QCFuR_yaGs0umyqHUDOZcOBKF8MFUGHX07txAW70z7wq_S9AKGQ_MixrLQ.png?r=a4b"

export const BG_IMAGE =
	"https://assets.nflxext.com/ffe/siteui/vlv3/a927b1ee-784d-494a-aa80-cf7a062d2523/web/IN-en-20250714-TRIFECTA-perspective_5acb7337-c372-45ec-ae12-ddb110e6ad78_large.jpg"

export const API_OPTIONS = {
	method: "GET",
	headers: {
		accept: "application/json",
		Authorization:
			"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhMzFhNGExMmRiYTdmMDM4OTczMmQ3NmZjZGQwZmQ4YSIsIm5iZiI6MTc1Mzc3NzcxNi4xMDYsInN1YiI6IjY4ODg4NjM0NDlmOWE0ZTZlZjcyZjg0MyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.NihPIyNklcj2lg4hU7DQj0ZPL_SHN4grPn8YmkiRAU4",
	},
}

export const IMG_CDN = "https://image.tmdb.org/t/p/w500/"

export const movies = [
	{
		adult: false,
		backdrop_path: "/8J6UlIFcU7eZfq9iCLbgc8Auklg.jpg",
		genre_ids: [14, 10751, 28],
		id: 1087192,
		original_language: "en",
		original_title: "How to Train Your Dragon",
		overview:
			"On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
		popularity: 663.8759,
		poster_path: "/53dsJ3oEnBhTBVMigWJ9tkA5bzJ.jpg",
		release_date: "2025-06-06",
		title: "How to Train Your Dragon",
		video: false,
		vote_average: 8.068,
		vote_count: 1369,
	},
	{
		adult: false,
		backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
		genre_ids: [16, 28, 14, 53],
		id: 1311031,
		original_language: "ja",
		original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
		overview:
			"As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
		popularity: 600.6803,
		poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
		release_date: "2025-07-18",
		title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
		video: false,
		vote_average: 6.913,
		vote_count: 46,
	},
	{
		adult: false,
		backdrop_path: "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
		genre_ids: [28, 878, 53],
		id: 1071585,
		original_language: "en",
		original_title: "M3GAN 2.0",
		overview:
			"After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
		popularity: 410.1184,
		poster_path: "/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
		release_date: "2025-06-25",
		title: "M3GAN 2.0",
		video: false,
		vote_average: 7.7,
		vote_count: 555,
	},
	{
		adult: false,
		backdrop_path: "/x5dVPttNDZaVRTvbk7pYrtGZoZN.jpg",
		genre_ids: [35],
		id: 1263256,
		original_language: "en",
		original_title: "Happy Gilmore 2",
		overview:
			"Happy Gilmore isn't done with golf — not by a long shot. Since his retirement after his first Tour Championship win, Gilmore returns to finance his daughter's ballet classes.",
		popularity: 421.1343,
		poster_path: "/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
		release_date: "2025-07-25",
		title: "Happy Gilmore 2",
		video: false,
		vote_average: 6.771,
		vote_count: 338,
	},
	{
		adult: false,
		backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
		genre_ids: [878, 12],
		id: 617126,
		original_language: "en",
		original_title: "The Fantastic 4: First Steps",
		overview:
			"Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
		popularity: 389.1212,
		poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
		release_date: "2025-07-23",
		title: "The Fantastic 4: First Steps",
		video: false,
		vote_average: 7.346,
		vote_count: 646,
	},
	{
		adult: false,
		backdrop_path: "/h6gChZHFpmbwqwV3uQsoakp77p1.jpg",
		genre_ids: [28, 35],
		id: 1124619,
		original_language: "en",
		original_title: "Bride Hard",
		overview:
			"Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
		popularity: 324.2053,
		poster_path: "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
		release_date: "2025-06-19",
		title: "Bride Hard",
		video: false,
		vote_average: 6.217,
		vote_count: 46,
	},
	{
		adult: false,
		backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
		genre_ids: [878, 12, 28],
		id: 1061474,
		original_language: "en",
		original_title: "Superman",
		overview:
			"Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
		popularity: 264.8351,
		poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
		release_date: "2025-07-09",
		title: "Superman",
		video: false,
		vote_average: 7.432,
		vote_count: 1303,
	},
	{
		adult: false,
		backdrop_path: "/962KXsr09uK8wrmUg9TjzmE7c4e.jpg",
		genre_ids: [28, 53, 18],
		id: 1119878,
		original_language: "en",
		original_title: "Ice Road: Vengeance",
		overview:
			"Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
		popularity: 263.2115,
		poster_path: "/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
		release_date: "2025-06-27",
		title: "Ice Road: Vengeance",
		video: false,
		vote_average: 6.819,
		vote_count: 152,
	},
	{
		adult: false,
		backdrop_path: "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
		genre_ids: [28, 12, 18],
		id: 1011477,
		original_language: "en",
		original_title: "Karate Kid: Legends",
		overview:
			"After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
		popularity: 259.4985,
		poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
		release_date: "2025-05-08",
		title: "Karate Kid: Legends",
		video: false,
		vote_average: 7.169,
		vote_count: 576,
	},
	{
		adult: false,
		backdrop_path: "/fQOV47FHTJdaSuSUNlzP3zXUZWE.jpg",
		genre_ids: [878, 12, 28],
		id: 1234821,
		original_language: "en",
		original_title: "Jurassic World Rebirth",
		overview:
			"Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
		popularity: 219.0006,
		poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
		release_date: "2025-07-01",
		title: "Jurassic World Rebirth",
		video: false,
		vote_average: 6.339,
		vote_count: 852,
	},
	{
		adult: false,
		backdrop_path: "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
		genre_ids: [28, 53, 80],
		id: 541671,
		original_language: "en",
		original_title: "Ballerina",
		overview:
			"Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
		popularity: 213.5048,
		poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
		release_date: "2025-06-04",
		title: "Ballerina",
		video: false,
		vote_average: 7.469,
		vote_count: 1208,
	},
	{
		adult: false,
		backdrop_path: "/9l6bcHNFLR2fcCBSPzEeqxiQhwU.jpg",
		genre_ids: [28, 35, 80, 9648],
		id: 1374534,
		original_language: "nl",
		original_title: "Bad Boa's",
		overview:
			"When an overeager community officer and a reckless ex-detective are forced to team up, plenty of chaos ensues on the streets of Rotterdam.",
		popularity: 177.5225,
		poster_path: "/7bcndiaTgu1Kj5a6qyCmsWYdtI.jpg",
		release_date: "2025-07-10",
		title: "Almost Cops",
		video: false,
		vote_average: 5.845,
		vote_count: 110,
	},
	{
		adult: false,
		backdrop_path: "/eNSUknQqzTXWE5EeT8ZnVccEPR0.jpg",
		genre_ids: [27, 53],
		id: 1285965,
		original_language: "en",
		original_title: "Dangerous Animals",
		overview:
			"A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.",
		popularity: 171.8534,
		poster_path: "/oQJ1PKLIE2gF5cr3xwjLCvv4jcU.jpg",
		release_date: "2025-06-05",
		title: "Dangerous Animals",
		video: false,
		vote_average: 6.504,
		vote_count: 112,
	},
	{
		adult: false,
		backdrop_path: "/6WqqEjiycNvDLjbEClM1zCwIbDD.jpg",
		genre_ids: [27, 53, 878],
		id: 1100988,
		original_language: "en",
		original_title: "28 Years Later",
		overview:
			"Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
		popularity: 187.9685,
		poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
		release_date: "2025-06-18",
		title: "28 Years Later",
		video: false,
		vote_average: 7.029,
		vote_count: 713,
	},
	{
		adult: false,
		backdrop_path: "/fd9K7ZDfzRAcbLh8JlG4HIKbtuR.jpg",
		genre_ids: [28, 14],
		id: 846422,
		original_language: "en",
		original_title: "The Old Guard 2",
		overview:
			"Andy and her team of immortal warriors fight with renewed purpose as they face a powerful new foe threatening their mission to protect humanity.",
		popularity: 134.0172,
		poster_path: "/wqfu3bPLJaEWJVk3QOm0rKhxf1A.jpg",
		release_date: "2025-07-01",
		title: "The Old Guard 2",
		video: false,
		vote_average: 6.03,
		vote_count: 575,
	},
	{
		adult: false,
		backdrop_path: "/vJbEUMeI2AxBUZKjP6ZVeVNNTLh.jpg",
		genre_ids: [28, 53, 35],
		id: 749170,
		original_language: "en",
		original_title: "Heads of State",
		overview:
			"The UK Prime Minister and US President have a public rivalry that risks their countries' alliance. But when they become targets of a powerful enemy, they're forced to rely on each other as they go on a wild, multinational run. Allied with Noel, a brilliant MI6 agent, they must find a way to thwart a conspiracy that threatens the free world.",
		popularity: 137.7144,
		poster_path: "/lVgE5oLzf7ABmzyASEVcjYyHI41.jpg",
		release_date: "2025-07-02",
		title: "Heads of State",
		video: false,
		vote_average: 6.959,
		vote_count: 599,
	},
	{
		adult: false,
		backdrop_path: "/lSbblLngbeZIn6G4WXDcyQ6SLhw.jpg",
		genre_ids: [28, 18],
		id: 911430,
		original_language: "en",
		original_title: "F1",
		overview:
			"Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
		popularity: 130.318,
		poster_path: "/6H6p82aWQFEKEuVUiZll6JxV8Ft.jpg",
		release_date: "2025-06-25",
		title: "F1",
		video: false,
		vote_average: 7.613,
		vote_count: 940,
	},
	{
		adult: false,
		backdrop_path: "/8aNNz9WYmxhnBxzWTt0nRI4F7rx.jpg",
		genre_ids: [10749, 18],
		id: 1241634,
		original_language: "hi",
		original_title: "सैयारा",
		overview:
			"Two artistic souls find harmony through music despite their contrasting worlds. As feelings deepen, age and circumstances challenge their undeniable bond.",
		popularity: 126.4401,
		poster_path: "/jymezcmEcFvlb037V4SSx8a4SMq.jpg",
		release_date: "2025-07-18",
		title: "Saiyaara",
		video: false,
		vote_average: 6.282,
		vote_count: 71,
	},
	{
		adult: false,
		backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
		genre_ids: [10749, 18],
		id: 1136867,
		original_language: "en",
		original_title: "Materialists",
		overview:
			"A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
		popularity: 108.1887,
		poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
		release_date: "2025-06-12",
		title: "Materialists",
		video: false,
		vote_average: 6.774,
		vote_count: 226,
	},
	{
		adult: false,
		backdrop_path: "/es0N3A6vkLz2EmJavnM2M4urOEO.jpg",
		genre_ids: [53, 27],
		id: 1026222,
		original_language: "en",
		original_title: "Saint Clare",
		overview:
			"In a small town a solitary woman is haunted by voices that lead her to assassinate ill intended people and get away with it, until her last kill sucks her down a rabbit hole riddled with corruption, trafficking and visions from the beyond.",
		popularity: 106.2967,
		poster_path: "/aE0q4awk7zto3Eql4cAeJuVAns9.jpg",
		release_date: "2025-07-18",
		title: "Saint Clare",
		video: false,
		vote_average: 5.2,
		vote_count: 13,
	},
]
